    - name: Clonar repositorio
      uses: appleboy/ssh-action@master
      with:
        host: 18.208.226.205
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliza el secreto correcto aquí
        script: |
          sudo git clone https://${{ secrets.GH_TOKEN }}@github.com/usuario/repo.git /opt/miDirectorio || exit 1

    - name: Instalar paquetes NPM
      uses: appleboy/ssh-action@master
      with:
        host: 18.208.226.205
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliza el secreto correcto aquí
        script: |
          cd /opt/miDirectorio
          sudo npm install express pm2 || exit 1

    - name: Iniciar servicio con PM2
      uses: appleboy/ssh-action@master
      with:
        host: 18.208.226.205
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliza el secreto correcto aquí
        script: |
          cd /opt/miDirectorio
          sudo pm2 start tu_app.js || exit 1

    - name: Chequear si la aplicación está corriendo
      uses: appleboy/ssh-action@master
      with:
        host: 18.208.226.205
        username: ec2-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}  # Utiliza el secreto correcto aquí
        script: |
          sudo pm2 status | grep tu_app.js || exit 1

